ver: 1
max-attempts: 3
debug: false
config:
  prefix: AuthAnvilLogin
  isRequestUpper: true
  checkLowestPassword: true
  checkLongestPassword: true
  enableAgreement: false
materials:
  login:
    left: "PAPER"
    right: "REDSTONE"
    output: "ARROW"
  register:
    left: "DIAMOND"
    right: "IRON_INGOT"
    output: "ARROW"
agreement:
  - ""