name: AuthAnvilLogin
version: '0.1-Beta1'
main: net.chen.ll.authAnvilLogin.AuthAnvilLogin
api-version: '1.20'
load: POSTWORLD
authors: [ Chen ]
depend:
  - AuthMe
description: Use anvil to login
website: i.whocare.life
